api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
    title: 'Two Factor Authentication API'
    description: 'Two Factor Authentication'
    version: 1.0
    show_webby: false
