version: '3.5'

services:
  two-factor-authentication-api-web:
    container_name: two-factor-authentication-api-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 8080:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - two-factor-authentication-api-be
    networks:
      - two-factor-authentication-api-network

  two-factor-authentication-api-be:
    container_name: two-factor-authentication-api-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - two-factor-authentication-api-db
    networks:
      - two-factor-authentication-api-network

  two-factor-authentication-api-db:
    container_name: two-factor-authentication-api-db
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: two-factor-authentication-api_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - two-factor-authentication-api-db-data:/var/lib/mysql
    networks:
      - two-factor-authentication-api-network

volumes:
  two-factor-authentication-api-db-data:

networks:
  two-factor-authentication-api-network:
