services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $roleValidators: !tagged app.role_validator

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Api\:
        resource: '../src/Api'
        tags: ['controller.service_arguments']

    App\Api\Listener\JsonExceptionResponseTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }